feat: Async init
strvcom/ios-dependency-injection pull request #19
Opened 2024-12-17 15:13 UTC by robha141

Added new AsyncContainer, with async registration and resolution of dependencies.

2025-01-03 20:06 UTC, cejanen requested changes
Well, I apologize for request changes, but I just wanna you double check the solution as well. There are many similarities in all those typealiases for "factories" but some of the types are not very understandable - although it's async copy paste of existing. 
I know we're adding  new "feature" without breaking changes, at the same time we created async DI for exploring swift6 complete concurrency check really fast way, therefore I'm for double check.

2025-01-06 09:01 UTC, robha141 commented on Package.swift
> +// swift-tools-version:5.8
my bad 😢

2025-01-06 09:01 UTC, robha141 commented on Sources/Models/AsyncRegistration.swift
> +    init<T: Sendable>(type: T.Type, scope: DependencyScope, factory: @Sendable @escaping (any AsyncDependencyResolving) async -> T) {
I just copied the naming as it was in sync implementation, it did make sense to me. I will revisit it 😄

2025-01-07 07:42 UTC, robha141 commented on Package.swift
> +// swift-tools-version:5.8
fixed 👍

2025-01-07 07:45 UTC, robha141 commented on Sources/Models/AsyncRegistration.swift
> +    init<T: Sendable>(type: T.Type, scope: DependencyScope, factory: @Sendable @escaping (any AsyncDependencyResolving) async -> T) {
Hmm, as I look into it, it kinda makes sense, because `AsyncDependencyResolving` has different factory then `AsyncRegistration`, due to the fact that there is an optional parameter in `AsyncRegistrationFactory`. I would keep it as it is, since nothing better comes to my mind at the moment 😄
I only changed property name, so it's not confusing and we can now distinguish between `asyncRegistrationFactory` and `factory` parameter 😄

2025-01-08 15:25 UTC, ipek submitted a review, later dismissed
Very handy! I have just a few documentation and tests comments.

2025-01-08 15:25 UTC, ipek commented on Sources/Protocols/Resolution/AsyncDependencyResolving.swift
> +    ///   - type: Type of the dependency that should be resolved
There is no `type` parameter.

2025-01-08 15:25 UTC, ipek commented on Sources/Protocols/Resolution/AsyncDependencyResolving.swift
> +    ///   - type: Type of the dependency that should be resolved
There is no `type` parameter.

2025-01-08 15:25 UTC, ipek commented on Tests/Container/AsyncComplexTests.swift
> +        XCTAssertNil(resolvedDependency1, "Shared instance wasn't released")
What is this testing 🤔?

2025-02-04 07:32 UTC, cernym46 reviewed
I just looked at it briefly and left one thought. I'll do more throught review once I have more time. 😊

2025-02-04 07:32 UTC, cernym46 commented on Sources/Container/AsyncContainer.swift
> +    ) async {
Originally, I thought that this PR is about anynchronous initialization of the dependency, meaning that I would expect that the factory closure is async 🤔

2025-02-04 07:32 UTC, cernym46 commented on Sources/Container/AsyncContainer.swift
> +public actor AsyncContainer: AsyncDependencyResolving, AsyncDependencyRegistering {
Would be possible to have just one `Container` with synchronous and asynchronous `register` & `resolve` functions? The `async` `resolve` would be "safe" whereas the synchronous one would crash if you tried to resolve `async` dependency.

This way would have the depevoler more freedom and not everything had to be wrapped in a Task.

2025-02-04 07:47 UTC, cernym46 commented on Tests/Common/Dependencies.swift
> +final class DependencyWithParameter5: Sendable {
Consider adding `DependencyWiyAsyncInit`. 

I haven't found a test where it would be tested asynchronous init in the factory closure. I saw only tests with asynchronous resolve in the factory closures.

2025-02-04 16:49 UTC, DanielCech reviewed
@robha141 Kudos. Impressive work. Please consider the change in the folder structure - maybe we can put Sync and Async variants of code into separate subfolders. What do you think?

And maybe silly question. If I have the same dependency that I need in both sync and async contexts, should I have two registrations? Can we somehow unify the interface as @cernym46 suggested?

2025-02-04 16:49 UTC, DanielCech commented on Sources/Protocols/Registration/AsyncDependencyRegistering.swift
> +    /// If you need to support this usecase, please, keep references to the variable singletons outside of the container.
Interesting discussion. I agree that shared registrations with arguments doesn't make sense.

2025-02-04 16:49 UTC, DanielCech commented on Tests/Container/AsyncComplexTests.swift
> +        XCTAssertNil(resolvedDependency1, "Shared instance wasn't released")
@ipek If I understand it correctly. At first, it creates shared dependency instances and tests whether they are the same. After that `releaseSharedInstances` is called and the newly created instance should not be the same as the first one because a new shared instance was created.

2025-02-06 09:16 UTC, DanielCech commented on Sources/Protocols/Resolution/AsyncDependencyResolving.swift
> +    ///   - type: Type of the dependency that should be resolved
Fixed.

2025-02-06 09:17 UTC, DanielCech commented on Sources/Protocols/Resolution/AsyncDependencyResolving.swift
> +    ///   - type: Type of the dependency that should be resolved
Fixed

2025-02-06 10:19 UTC, DanielCech commented on Tests/Common/Dependencies.swift
> +final class DependencyWithParameter5: Sendable {
@cernym46 I added `DependencyWithAsyncInit` and `testRegistrationWithAsyncInit` that covers this case.

2025-02-14 06:46 UTC, robha141 commented on Sources/Container/AsyncContainer.swift
> +public actor AsyncContainer: AsyncDependencyResolving, AsyncDependencyRegistering {
I don't think so 😢 
When you think about it, I can store resolvers as `Any` and try to downcast when resolving to either async or non async one. But what will it bring ? In the end more unexpected crashes, when you change sync resolver to async one in larger app on some weird place. I can see that this can easily happen and the tradeoff from coding part is not that beneficial 😄

2025-02-14 06:48 UTC, robha141 commented on Sources/Protocols/Registration/AsyncDependencyRegistering.swift
> +    /// If you need to support this usecase, please, keep references to the variable singletons outside of the container.
this is old commend by @schwarja 😄 I implemented DI container in the past in previous company, it looked pretty much the same and here I just copied his solution 😄

2025-02-17 13:59 UTC, ipek submitted a review, later dismissed
Great job! I didn't find anything that would have effect on the usage. Just few naming/documentation notes and one nitpicking edgecase.

2025-02-17 13:59 UTC, ipek commented on Tests/Container/Async/AsyncArgumentTests.swift
> +        }
Please rename the test method. This is implicit/inferred type. Or not?

2025-02-17 13:59 UTC, ipek commented on Tests/Container/Async/AsyncBaseTests.swift
> +    func testUnregisteredDependency() async {
This test method seems incomplete. I would guess it should test that container is cleaned up if you call the method? Otherwise you just tests that the parent test case class is doing a cleanup.

2025-02-17 13:59 UTC, ipek commented on Sources/Container/Async/AsyncContainer.swift
> +    // MARK: Register dependency, Autoregister dependency
```suggestion
    // MARK: Register dependency
```

2025-02-17 13:59 UTC, ipek commented on Sources/Container/Async/AsyncContainer.swift
> +    // MARK: Register dependency with argument, Autoregister dependency with argument
```suggestion
    // MARK: Register dependency with argument
```

2025-02-17 13:59 UTC, ipek commented on Sources/Container/Async/AsyncContainer.swift
> +        registrations[registration.identifier] = registration
Is it possible that developer will get to a state where they previously registered shared instance (factory without a parameter) and now they will end up with shared instance in the cache? Should we release the identifier from cache here?

2025-02-18 08:02 UTC, cernym46 commented on Sources/Container/AsyncContainer.swift
> +public actor AsyncContainer: AsyncDependencyResolving, AsyncDependencyRegistering {
Ok 🙂 I think we should be good without the synchronous version.

2025-02-19 09:17 UTC, DanielCech commented on Tests/Container/Async/AsyncArgumentTests.swift
> +        }
@ipek In my understanding, when the type is explicitly mentioned in the register method, it should be "explicit".

2025-02-19 09:25 UTC, DanielCech commented on Tests/Container/Async/AsyncBaseTests.swift
> +    func testUnregisteredDependency() async {
@ipek I think the meaning of this test is different. It tests that resolving type `SimpleDependency` will fail when this type is not registered. There is no cleanup in this code.

2025-02-19 09:43 UTC, DanielCech commented on Sources/Container/Async/AsyncContainer.swift
> +        registrations[registration.identifier] = registration
I think this can't happen. The registration identifier consists of type and argument `ObjectIdentifier`s, so those two registrations are different. I think it is the user's responsibility to handle registrations and this should (in my understanding) behave correctly.

2025-02-19 10:46 UTC, DanielCech commented on Tests/Container/AsyncComplexTests.swift
> +        XCTAssertNil(resolvedDependency1, "Shared instance wasn't released")
@ipek You are right. I agree that it was the intended meaning. I've fixed it in both AsyncComplexTests and ComplexTests.

2025-02-19 12:11 UTC, ipek commented on Tests/Container/Async/AsyncArgumentTests.swift
> +        }
True, my bad.

2025-02-19 12:11 UTC, ipek approved these changes

2025-02-19 14:26 UTC, cejanen approved these changes
🍚

2025-02-19 14:51 UTC, merged